export const ENVIROMENTS = {
  SPOTIFY_ACCOUNTS: process.env.NEXT_PUBLIC_SPOTIFY_ACCOUNTS,
  SPOTIFY_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.NEXT_PUBLIC_CLIENT_SECRET,
  SPOTIFY_API: process.env.NEXT_PUBLIC_SPOTIFY_API,
};
